import type { GlobalConfiguration, QuartzComponentProps } from "@quartz-community/types"
import type { VNode } from "preact"
import render from "preact-render-to-string"
import { afterEach, describe, expect, it, vi } from "vitest"
import WikiCommitBannerConstructor from "./WikiCommitBanner"

const WikiCommitBanner = WikiCommitBannerConstructor()

type BannerTestOptions = {
  slug?: string
  relativePath?: string
  cfg?: Partial<GlobalConfiguration>
  allFiles?: Array<{ relativePath?: string; slug?: string; frontmatter?: Record<string, unknown> }>
}

function makeProps(
  frontmatter: Record<string, unknown>,
  options: BannerTestOptions = {},
): QuartzComponentProps {
  return {
    fileData: { frontmatter, slug: options.slug, relativePath: options.relativePath },
    cfg: options.cfg,
    allFiles: options.allFiles ?? [],
  } as unknown as QuartzComponentProps
}

function renderBanner(frontmatter: Record<string, unknown>, options: BannerTestOptions = {}): string | null {
  const result = WikiCommitBanner(makeProps(frontmatter, options))
  if (result === null) return null
  return render(result as VNode)
}

describe("WikiCommitBanner", () => {
  afterEach(() => {
    vi.unstubAllEnvs()
  })

  it("renders the pending banner when review_status is pending", () => {
    const html = renderBanner({ title: "山田太郎", review_status: "pending" })
    expect(html).toContain("wikicommit-banner--pending")
    expect(html).toContain("This page was generated by an LLM")
  })

  it("makes no claim about reading on a pending page", () => {
    // Issue #774: "Nobody has read this page yet" was false in front of the
    // person reading it — what it actually reported was that no read by someone
    // with write access had been recorded, a distinction most readers do not
    // hold. The state is carried by the absence of the read line instead.
    const html = renderBanner({ title: "山田太郎", review_status: "pending" })
    for (const claim of ["Nobody has read", "nobody has read", "read this page yet"]) {
      expect(html).not.toContain(claim)
    }
    expect(html).not.toContain("A person read this page — nothing obviously wrong stood out")
    expect(html).not.toContain("nothing obviously wrong stood out")
  })

  it("treats a missing review_status as pending", () => {
    const html = renderBanner({ title: "山田太郎" })
    expect(html).toContain("wikicommit-banner--pending")
  })

  // Issue #663: `reviewed` said a review happened without saying whose judgment
  // it was — the reviewer's name existed only as a git commit trailer, which no
  // reader of the published site sees.
  describe("reviewer attribution on a reviewed page", () => {
    it("names the reviewer and links to their GitHub profile", () => {
      const html = renderBanner({
        title: "山田太郎",
        review_status: "reviewed",
        reviewed_by: "octocat",
      })
      expect(html).toContain("nothing obviously wrong stood out")
      expect(html).toContain('href="https://github.com/octocat"')
      expect(html).toContain(">octocat<")
    })

    it("falls back to the previous markup when the field is absent", () => {
      const withField = renderBanner({
        title: "山田太郎",
        review_status: "reviewed",
        reviewed_by: "octocat",
      })
      const without = renderBanner({ title: "山田太郎", review_status: "reviewed" })
      // Pages reviewed before the field existed are not back-filled, and a wiki
      // that never runs review-issue-close-sync.yml never gets one — so absence
      // is the normal state, not a gap worth labelling. It must not surface as
      // an empty label or as the "unknown" placeholder the pending branch uses.
      expect(without).not.toContain("nothing obviously wrong stood out")
      expect(without).not.toContain("unknown")
      expect(without).not.toBe(withField)
      expect(without).toContain("Report something you noticed")
    })

    it("ignores a present-but-blank value rather than rendering an empty link", () => {
      // The report link's own href is a github.com URL whenever
      // GITHUB_REPOSITORY is set, and GitHub Actions sets it on every step —
      // so the "no github.com link at all" assertion below only means "no
      // reviewer link" once the variable is stubbed away (same trap the
      // review-status-link suite documents).
      vi.stubEnv("GITHUB_REPOSITORY", undefined)
      const html = renderBanner({
        title: "山田太郎",
        review_status: "reviewed",
        reviewed_by: "   ",
      })
      expect(html).not.toContain("nothing obviously wrong stood out")
      expect(html).not.toContain("https://github.com/")
    })

    it("ignores a non-string value", () => {
      const html = renderBanner({ title: "山田太郎", review_status: "reviewed", reviewed_by: 42 })
      expect(html).not.toContain("nothing obviously wrong stood out")
    })

    it("does not show a reviewer on a pending page", () => {
      // A pending page has no reviewer by definition; a stale value left behind
      // by a regeneration (which returns the page to pending) must not read as
      // if someone had reviewed this version.
      // Stubbed for the same reason as above: the report link is a github.com
      // URL under an ambient GITHUB_REPOSITORY, so leaving it unstubbed would
      // make this assertion depend on the repository the tests happen to run in.
      vi.stubEnv("GITHUB_REPOSITORY", undefined)
      const html = renderBanner({
        title: "山田太郎",
        review_status: "pending",
        reviewed_by: "octocat",
      })
      expect(html).toContain("wikicommit-banner--pending")
      expect(html).not.toContain("nothing obviously wrong stood out")
      expect(html).not.toContain("https://github.com/octocat")
    })

    it("renders nothing on a removed page even with a reviewer", () => {
      const html = renderBanner({
        title: "山田太郎",
        review_status: "reviewed",
        reviewed_by: "octocat",
        status: "removed",
      })
      expect(html).toBeNull()
    })

    it("uses the Japanese label on a ja page", () => {
      const html = renderBanner({
        title: "山田太郎",
        lang: "ja",
        review_status: "reviewed",
        reviewed_by: "octocat",
      })
      expect(html).toContain("が読み、明らかな問題は見つかりませんでした")
    })
  })

  it("renders only the report link on a reviewed page that records no generation", () => {
    // This is the shape a build-generated index page has: rebuild_index.py
    // stamps `review_status: reviewed` on it precisely to keep this banner
    // quiet (Issue #580), and it carries no generation stamp because no model
    // wrote it. Issue #739 keys the banner on the stamp rather than on
    // review_status so those pages keep exactly this markup.
    const html = renderBanner({ title: "山田太郎", review_status: "reviewed" })
    expect(html).not.toContain("wikicommit-banner--pending")
    expect(html).not.toContain("wikicommit-banner--reviewed")
    expect(html).toContain("wikicommit-banner__report")
    expect(html).toContain("Report something you noticed")
    expect(html).not.toContain("This page was generated by an LLM")
  })

  // Issue #739: review-issue-close-sync.yml rewrites `review_status` and
  // `reviewed_by` and nothing else, so a page does not stop being LLM-written
  // when someone closes its tracking Issue — yet the banner used to drop every
  // trace of that fact at exactly that moment.
  describe("a reviewed page keeps saying it was generated", () => {
    const reviewedPage = {
      title: "山田太郎",
      review_status: "reviewed",
      generated_at: "2026-09-01",
      generated_by: "claude-opus-5",
      lang: "en",
    }

    it("still states that the page was written by a model", () => {
      const html = renderBanner(reviewedPage)
      expect(html).toContain("This page was generated by an LLM")
      expect(html).toContain("2026-09-01")
      expect(html).toContain("claude-opus-5")
    })

    it("says the same thing a pending page says, word for word", () => {
      // The fact is identical in both states; softening it here would be the
      // over-claim this change exists to remove.
      const pending = renderBanner({ ...reviewedPage, review_status: "pending" })
      const reviewed = renderBanner(reviewedPage)
      // Issue #774 split the fact from what follows from it, so the heading and
      // the body are checked as the pair they now form.
      const heading = "This page was generated by an LLM"
      const body = "It may contain inaccuracies."
      expect(pending).toContain(heading)
      expect(reviewed).toContain(heading)
      expect(pending).toContain(body)
      expect(reviewed).toContain(body)
    })

    it("stays visually distinguishable from a pending page", () => {
      // Without this a reader cannot tell whether anyone has read the page,
      // which is the whole point of showing `reviewed` at all. Two signals
      // carry it now that the heading no longer swaps (Issue #774): the
      // modifier class (border colour) and the presence of the read line.
      const pending = renderBanner({ ...reviewedPage, review_status: "pending" })
      const reviewed = renderBanner(reviewedPage)
      expect(pending).toContain("wikicommit-banner--pending")
      expect(reviewed).toContain("wikicommit-banner--reviewed")
      expect(pending).not.toContain("wikicommit-banner__reviewer")
      expect(reviewed).toContain("wikicommit-banner__reviewer")
    })

    it("tells the two states apart without depending on reviewed_by", () => {
      // A route B page has no login to record (`/wikicommit-review` runs
      // locally), so a distinction resting on the reviewer's name would leave
      // those pages indistinguishable from pending ones (Issue #774). The line
      // states the fact on its own rather than an empty label or an `unknown`
      // placeholder: a missing reviewer is a normal state, not a gap to fill
      // (Issue #663).
      // The named form (`readBy`) is what carries a profile link, so its absence
      // is what tells the two forms apart now that both say what the reading
      // found (Issue #800 — the old assertion compared the label "Read by:",
      // which no longer exists as a standalone label). Stubbed for the same
      // reason the two assertions above it are: the report link's own href is a
      // github.com URL whenever GITHUB_REPOSITORY is set, and GitHub Actions
      // sets it on every step, so leaving it unstubbed makes "no github.com
      // link at all" fail in CI while passing locally.
      vi.stubEnv("GITHUB_REPOSITORY", undefined)
      const reviewed = renderBanner(reviewedPage)
      expect(reviewed).not.toContain("https://github.com/")
      expect(reviewed).toContain("A person read this page — nothing obviously wrong stood out")
      expect(reviewed).not.toContain("unknown")
    })

    it("keeps the warning icon in both states", () => {
      // Issue #774: the ⚠️ used to belong to "nobody has read this yet". With
      // that claim gone it belongs to the heading — being written by a model —
      // which review does not end. Keeping it pending-only would encode "the
      // warning is retracted at review", the reading Issue #739 denied.
      expect(renderBanner({ ...reviewedPage, review_status: "pending" })).toContain("⚠️")
      expect(renderBanner(reviewedPage)).toContain("⚠️")
    })

    it("adds the reviewer rather than replacing anything", () => {
      const html = renderBanner({ ...reviewedPage, reviewed_by: "octocat" })
      expect(html).toContain("nothing obviously wrong stood out")
      expect(html).toContain('href="https://github.com/octocat"')
      // The generation facts are still there alongside it.
      expect(html).toContain("claude-opus-5")
    })

    it("states the reviewer instead of the fallback when a name is recorded", () => {
      // Issue #774: printing both would say "read" twice — the `Read by:` line
      // already carries that a person read it, and says who.
      const html = renderBanner({ ...reviewedPage, reviewed_by: "octocat" })
      expect(html).toContain("nothing obviously wrong stood out")
      expect(html).not.toContain("A person read this page — nothing obviously wrong stood out")
    })

    it("shows translation stamps on a reviewed translation page", () => {
      const html = renderBanner({
        title: "Taro Yamada",
        review_status: "reviewed",
        lang: "en",
        translated_from: ".wikicommit/entity/ja/Person/yamada-taro.md",
        translated_at: "2026-09-02",
        translated_by: "claude-opus-5",
      })
      expect(html).toContain("Translated:")
      expect(html).toContain("2026-09-02")
      expect(html).toContain("wikicommit-banner--reviewed")
    })

    it("stays quiet on a reviewed translation page whose translation stamps are missing", () => {
      // The stamp check has to look at the same pair the banner will print.
      // A translation page renders translated_at/translated_by and nothing
      // else, so if generated_at/generated_by could open the gate for one,
      // the reviewed banner would appear reading "Translated: unknown
      // Model: unknown" — a generation notice with no generation data in it,
      // which is exactly what this gate exists to keep off a stamp-less
      // reviewed page.
      const html = renderBanner({
        title: "Taro Yamada",
        review_status: "reviewed",
        lang: "en",
        translated_from: ".wikicommit/entity/ja/Person/yamada-taro.md",
        generated_at: "2026-09-01",
        generated_by: "claude-opus-5",
      })
      expect(html).not.toContain("wikicommit-banner--reviewed")
      expect(html).not.toContain("unknown")
      expect(html).toContain("wikicommit-banner__report")
    })

    it("stays quiet on a reviewed ordinary page carrying only translation stamps", () => {
      // The mirror of the case above: an ordinary page prints
      // generated_at/generated_by, so a stray translated_* must not open the
      // gate onto "Generated: unknown  Model: unknown" either.
      const html = renderBanner({
        title: "山田太郎",
        review_status: "reviewed",
        lang: "en",
        translated_at: "2026-09-02",
        translated_by: "claude-opus-5",
      })
      expect(html).not.toContain("wikicommit-banner--reviewed")
      expect(html).not.toContain("unknown")
      expect(html).toContain("wikicommit-banner__report")
    })
  })

  it("displays generated_at and generated_by when present", () => {
    const html = renderBanner({
      review_status: "pending",
      generated_at: "2026-06-17",
      generated_by: "claude-sonnet-4-6",
    })
    expect(html).toContain("2026-06-17")
    expect(html).toContain("claude-sonnet-4-6")
  })

  it("falls back to the locale's unknown label when generated_at / generated_by are missing", () => {
    const html = renderBanner({ review_status: "pending" })
    expect(html).toContain("unknown")
  })

  // Issue #453: translation pages carry translated_at/translated_by (a distinct
  // event from generation) instead of generated_at/generated_by, which they
  // never had. Before this fix, every translated page's pending banner showed
  // "unknown" for both fields unconditionally.
  it("displays translated_at and translated_by (under the Translated:/Model: labels) on a translation page", () => {
    const html = renderBanner({
      review_status: "pending",
      translated_from: ".wikicommit/entity/ja/Person/yamada-taro.md",
      translated_at: "2026-07-01",
      translated_by: "claude-sonnet-4-6",
    })
    expect(html).toContain("Translated:")
    expect(html).toContain("2026-07-01")
    expect(html).toContain("claude-sonnet-4-6")
    expect(html).not.toContain("Generated:")
  })

  it("falls back to the locale's unknown label when translated_at / translated_by are missing on a translation page", () => {
    const html = renderBanner({
      review_status: "pending",
      translated_from: ".wikicommit/entity/ja/Person/yamada-taro.md",
    })
    expect(html).toContain("Translated:")
    expect(html).toContain("unknown")
  })

  it("does not use translation labels/fields for an ordinary (non-translated) page", () => {
    const html = renderBanner({
      review_status: "pending",
      generated_at: "2026-06-17",
      generated_by: "claude-sonnet-4-6",
    })
    expect(html).toContain("Generated:")
    expect(html).not.toContain("Translated:")
  })

  // Issue #579: the banner said the page was unreviewed without offering any
  // way to reach the place that review actually happens.
  describe("review-status search link (Issue #579)", () => {
    const pendingPage = {
      title: "山田太郎",
      review_status: "pending",
      type: "schema:Person",
      lang: "ja",
    }
    const pageLocation = { relativePath: "ja/Person/yamada-taro.md" }

    function reviewLinkHref(html: string | null): string | undefined {
      return html?.match(/href="([^"]*\/issues\?q=[^"]*)"/)?.[1]
    }

    function searchQuery(html: string | null): string {
      const href = reviewLinkHref(html)
      expect(href).toBeDefined()
      return decodeURIComponent(href!.split("?q=")[1] ?? "")
    }

    it("links to a review-tracking Issue search on a pending page", () => {
      // The label follows the page's own lang, like every other caption here.
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const html = renderBanner(pendingPage, pageLocation)
      expect(html).toContain("このページのレビュー状況を見る")
      expect(reviewLinkHref(html)).toContain("https://github.com/wikicommit-dev/example-wiki/issues?q=")
    })

    it("labels the link in English on an English page", () => {
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const html = renderBanner(
        { review_status: "pending", type: "schema:Person", lang: "en" },
        { relativePath: "en/Person/yamada-taro.md" },
      )
      expect(html).toContain("Check this page's review status")
      expect(searchQuery(html)).toContain('"Person/yamada-taro (en)"')
    })

    it("filters the search by open state, the tracking label and the title", () => {
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const query = searchQuery(renderBanner(pendingPage, pageLocation))
      // is:open is what keeps a regenerated page (which gets a *new* tracking
      // Issue) from pointing at the closed one left behind by the last round.
      expect(query).toContain("is:open")
      expect(query).toContain("label:wikicommit-review")
      expect(query).toContain("in:title")
      expect(query).toContain('"Person/yamada-taro (ja)"')
    })

    it("keys the search on type/slug/lang, never on the page title", () => {
      // A regeneration can change `title` while type/slug/lang stay fixed, so
      // a title-keyed link would go stale every time a page is rebuilt.
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const query = searchQuery(renderBanner(pendingPage, pageLocation))
      expect(query).not.toContain("山田太郎")
    })

    it("keeps a custom type's full type name in the search key", () => {
      // Publishing drops the custom/ segment from the *path* (Issue #576), but
      // wikicommit-merge titles the Issue with the frontmatter type, which
      // keeps it.
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const html = renderBanner(
        { review_status: "pending", type: "schema:custom/Decision", lang: "ja" },
        { relativePath: "ja/Decision/adopt-quartz.md" },
      )
      expect(searchQuery(html)).toContain('"custom/Decision/adopt-quartz (ja)"')
    })

    it("does not offer the link on a reviewed page", () => {
      // Its tracking Issue is closed; the report link stays for reporting an
      // error found later (Issue #245).
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const html = renderBanner({ ...pendingPage, review_status: "reviewed" }, pageLocation)
      expect(html).not.toContain("このページのレビュー状況を見る")
      expect(reviewLinkHref(html)).toBeUndefined()
      expect(html).toContain("気づいた点を報告する")
    })

    it("renders nothing at all on a removed page, as before", () => {
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      expect(renderBanner({ ...pendingPage, status: "removed" }, pageLocation)).toBeNull()
    })

    it("omits the link when GITHUB_REPOSITORY is unset", () => {
      // The report link keeps its historical "#" fallback; this one is dropped
      // instead, since a search URL with no repository cannot be made to point
      // anywhere meaningful.
      // Stub the variable away rather than relying on the ambient environment:
      // GitHub Actions sets GITHUB_REPOSITORY on every step, so an unstubbed
      // read would see the real repository and this assertion would fail in CI
      // while passing locally.
      vi.stubEnv("GITHUB_REPOSITORY", undefined)
      const html = renderBanner(pendingPage, pageLocation)
      expect(html).toContain("wikicommit-banner--pending")
      expect(reviewLinkHref(html)).toBeUndefined()
    })

    it("omits the link when the search key cannot be built", () => {
      // type, lang and the file path are each required. Quartz's own folder
      // and tag pages have none of them (no frontmatter), and no tracking
      // Issue either, so they must not get a link that always finds nothing.
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      expect(reviewLinkHref(renderBanner({ review_status: "pending" }, {}))).toBeUndefined()
      expect(
        reviewLinkHref(renderBanner({ review_status: "pending", lang: "ja" }, pageLocation)),
      ).toBeUndefined()
      expect(
        reviewLinkHref(renderBanner({ review_status: "pending", type: "schema:Person" }, pageLocation)),
      ).toBeUndefined()
      expect(reviewLinkHref(renderBanner(pendingPage, {}))).toBeUndefined()
    })
  })

  // Issue #528: isTranslation previously only switched the Translated:/Model:
  // captions — a reader-filed Issue on a translation page carried no signal
  // that the page is a translation, or where the original lives.
  describe("original page pointer in the report body (Issue #528)", () => {
    it("links to the original page's own public URL when it resolves via allFiles", () => {
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const html = renderBanner(
        {
          title: "Taro Yamada",
          review_status: "reviewed",
          translated_from: ".wikicommit/entity/ja/Person/yamada-taro.md",
        },
        {
          slug: "en/person/yamada-taro",
          cfg: { baseUrl: "example.github.io/wiki" },
          allFiles: [
            {
              relativePath: "ja/Person/yamada-taro.md",
              slug: "ja/person/yamada-taro",
              frontmatter: { title: "山田太郎" },
            },
          ],
        },
      )
      expect(html).toContain(
        encodeURIComponent("Original page: https://example.github.io/wiki/ja/person/yamada-taro"),
      )
    })

    it("resolves the original page of a translated custom-type page, whose published path drops custom/", () => {
      // convert_wikilinks.py writes .wikicommit/entity/ja/custom/Decision/x.md
      // to content/ja/Decision/x.md (Issue #576), so `relativePath` never
      // carries the custom/ segment translated_from does. Without the same
      // flattening here the lookup misses and the banner quietly degrades to
      // the raw-path fallback below.
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const html = renderBanner(
        {
          title: "Adopting Quartz",
          review_status: "reviewed",
          translated_from: ".wikicommit/entity/ja/custom/Decision/adopt-quartz.md",
        },
        {
          slug: "en/decision/adopt-quartz",
          cfg: { baseUrl: "example.github.io/wiki" },
          allFiles: [
            {
              relativePath: "ja/Decision/adopt-quartz.md",
              slug: "ja/decision/adopt-quartz",
              frontmatter: { title: "Quartz の採用" },
            },
          ],
        },
      )
      expect(html).toContain(
        encodeURIComponent("Original page: https://example.github.io/wiki/ja/decision/adopt-quartz"),
      )
    })

    it("falls back to the raw translated_from path when the parent isn't found in allFiles", () => {
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const html = renderBanner(
        {
          title: "Taro Yamada",
          review_status: "reviewed",
          translated_from: ".wikicommit/entity/ja/Person/yamada-taro.md",
        },
        { cfg: { baseUrl: "example.github.io/wiki" } },
      )
      expect(html).toContain(
        encodeURIComponent("Original page: .wikicommit/entity/ja/Person/yamada-taro.md"),
      )
    })

    it("falls back to the raw translated_from path when cfg.baseUrl is unset", () => {
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const html = renderBanner(
        {
          title: "Taro Yamada",
          review_status: "reviewed",
          translated_from: ".wikicommit/entity/ja/Person/yamada-taro.md",
        },
        {
          allFiles: [{ relativePath: "ja/Person/yamada-taro.md", slug: "ja/person/yamada-taro" }],
        },
      )
      expect(html).toContain(
        encodeURIComponent("Original page: .wikicommit/entity/ja/Person/yamada-taro.md"),
      )
    })

    it("falls back to the raw translated_from path when the original page itself is status: removed", () => {
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const html = renderBanner(
        {
          title: "Taro Yamada",
          review_status: "reviewed",
          translated_from: ".wikicommit/entity/ja/Person/yamada-taro.md",
        },
        {
          cfg: { baseUrl: "example.github.io/wiki" },
          allFiles: [
            {
              relativePath: "ja/Person/yamada-taro.md",
              slug: "ja/person/yamada-taro",
              frontmatter: { status: "removed" },
            },
          ],
        },
      )
      expect(html).toContain(
        encodeURIComponent("Original page: .wikicommit/entity/ja/Person/yamada-taro.md"),
      )
    })

    it("omits the Original page line entirely for an ordinary (non-translated) page", () => {
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const html = renderBanner({ title: "OpenAI", review_status: "reviewed" })
      expect(html).not.toContain(encodeURIComponent("Original page:"))
    })

    it("uses the ja-JP label for the original-page line when cfg.locale is ja-JP", () => {
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const html = renderBanner(
        {
          title: "山田太郎",
          lang: "ja",
          review_status: "reviewed",
          translated_from: ".wikicommit/entity/en/Person/taro-yamada.md",
        },
        { cfg: { locale: "ja-JP" } },
      )
      expect(html).toContain(
        encodeURIComponent("原文ページ: .wikicommit/entity/en/Person/taro-yamada.md"),
      )
    })
  })

  it("includes the type (schema name) in the report issue title", () => {
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const html = renderBanner({
      title: "OpenAI",
      type: "schema:Organization",
      review_status: "reviewed",
    })
    expect(html).toContain(encodeURIComponent("[Report] Organization: OpenAI"))
  })

  it("omits the type segment when frontmatter.type is absent", () => {
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const html = renderBanner({ title: "OpenAI", review_status: "reviewed" })
    expect(html).toContain(encodeURIComponent("[Report] OpenAI"))
  })

  it("prefills the issue body with the canonical page URL and language", () => {
    // lang: "ja" with no cfg.locale set: the report body's own "Language: ja"
    // line is a literal echo of frontmatter.lang regardless of locale, but
    // the *labels* ("ページ:"/"言語:") now follow frontmatter.lang too
    // (Issue #378) rather than defaulting to English absent an explicit
    // cfg.locale, which is exactly the behavior under test here.
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const html = renderBanner(
      { title: "OpenAI", type: "schema:Organization", lang: "ja", review_status: "reviewed" },
      { slug: "ja/organization/openai", cfg: { baseUrl: "example.github.io/wiki" } },
    )
    // The facts are the first two lines; Issue #738 appends reporting guidance
    // after them, so this asserts the prefix rather than the whole body.
    const expectedFacts = ["ページ: https://example.github.io/wiki/ja/organization/openai", "言語: ja"].join(
      "\n",
    )
    expect(html).toContain(`body=${encodeURIComponent(expectedFacts)}`)
  })

  // Issue #738: the two checklist items Issue #723 marked "only a person can
  // check this" were written down only in the review-tracking Issue, which is
  // read by whoever browses the repository's Issue list — in practice the
  // operator. The person most likely to notice the harm item is usually the
  // subject of the page, who never opens that list but does read the page.
  it("prefills the issue body with what this wiki is asking readers to look for", () => {
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const html = renderBanner(
      { title: "OpenAI", type: "schema:Organization", lang: "en", review_status: "reviewed" },
      { slug: "en/organization/openai", cfg: { baseUrl: "example.github.io/wiki" } },
    )
    expect(html).toContain(
      encodeURIComponent("These are the kinds of problem no automated check can find"),
    )
    expect(html).toContain(
      encodeURIComponent("- Anything about a real person or organization that felt overstated"),
    )
    expect(html).toContain(encodeURIComponent("- Anything that conflicts with what you know"))
    expect(html).toContain(
      encodeURIComponent("- Anything another page on this wiki says differently"),
    )
  })

  it("does not present the guidance as the only things worth reporting", () => {
    // A closed list would turn a typo, a stale fact or a dead link into
    // something the reader concludes is unwanted.
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const html = renderBanner({ title: "OpenAI", lang: "en", review_status: "reviewed" })
    expect(html).toContain(encodeURIComponent("Anything else is welcome too"))
  })

  it("does not ask the reader to go and research", () => {
    // The same rule the tracking-Issue checklist follows (Issue #723): "tell us
    // if you know" costs nothing, "go and find out" makes every report an
    // open-ended search.
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const html = renderBanner({ title: "OpenAI", lang: "en", review_status: "reviewed" })
    expect(html).toContain(encodeURIComponent("you are not being asked to go looking"))
  })

  it("writes the guidance in the page's own language", () => {
    // The reason this lives in i18n strings rather than in
    // .github/ISSUE_TEMPLATE/report.md: that file is one per repository and has
    // no language, so a Japanese reader arriving through this link would get
    // English prompts.
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const html = renderBanner(
      { title: "OpenAI", lang: "ja", review_status: "reviewed" },
      { cfg: { locale: "en-US" } },
    )
    expect(html).toContain(encodeURIComponent("以下は自動チェックでは見つけられない種類の問題です"))
    expect(html).toContain(encodeURIComponent("- 実在の人物・組織について、書きすぎ・断定しすぎに感じた箇所"))
    expect(html).not.toContain(encodeURIComponent("These are the kinds of problem"))
  })

  it("keeps the guidance out of the report a reader ends up submitting", () => {
    // The same prompts in .github/ISSUE_TEMPLATE/report.md are HTML comments
    // and vanish on submit; a `body=` prefill is ordinary text and would not.
    // /wikicommit-fix reads an Issue's whole body as the feedback and
    // classifies "each distinct point" in it, so three standing bullets left in
    // every report become three points it tries to act on.
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const html = renderBanner({ title: "OpenAI", lang: "en", review_status: "reviewed" })
    expect(html).toContain(
      encodeURIComponent(
        [
          "<!--",
          "These are the kinds of problem no automated check can find. Write down any that apply (you are not being asked to go looking — only what you noticed while reading).",
        ].join("\n"),
      ),
    )
    expect(html).toContain(encodeURIComponent("broken links.\n-->"))
  })

  it("gives the reporter a marked place to write", () => {
    // `body=` replaces report.md's own `## Page` / `## Problem` headings
    // outright, so the prefilled body has to carry one itself or it ends at the
    // guidance with nowhere obvious to type. The page facts need no heading —
    // each of those lines already labels itself.
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const en = renderBanner({ title: "OpenAI", lang: "en", review_status: "reviewed" })
    expect(en).toContain(encodeURIComponent("## Problem"))
    const ja = renderBanner({ title: "OpenAI", lang: "ja", review_status: "reviewed" })
    expect(ja).toContain(encodeURIComponent("## 報告内容"))
  })

  it("does not put the guidance in the banner itself", () => {
    // Deliberate (Issue #738): on the banner these two prompts would show on
    // every page on every visit, which is how a standing notice stops being
    // read. They appear only once someone has decided to report. Checking the
    // rendered text outside the href keeps the banner's visual weight fixed.
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const html = renderBanner({ title: "OpenAI", lang: "en", review_status: "pending" })
    expect(html).not.toBeNull()
    const visible = (html as string).replace(/href="[^"]*"/g, "")
    expect(visible).not.toContain("These are the kinds of problem")
    expect(visible).not.toContain("- Anything that conflicts with what you know")
    expect(visible).not.toContain("[ ]")
  })

  it("keeps the prefilled URL well inside what GitHub accepts", () => {
    // Issue #738 measured GitHub's limit for /issues/new?...&body= on a public
    // repository: ~6KB still returns 200, ~7KB drops the connection and ~16KB
    // is a 414. Japanese is the worst case — one character is 3 bytes in UTF-8
    // and 9 once percent-encoded — so it is the language asserted here.
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const html = renderBanner(
      { title: "さいたま市立浦和図書館", type: "schema:Place", lang: "ja", review_status: "reviewed" },
      { slug: "ja/place/urawa-library", cfg: { baseUrl: "example.github.io/saitama-city-wiki" } },
    )
    expect(html).not.toBeNull()
    const href = /href="([^"]*)"/.exec((html as string).replace(/&amp;/g, "&"))?.[1]
    expect(href).toBeDefined()
    // Measured at 2,209 bytes with this wording — roughly 2.7x headroom.
    expect((href as string).length).toBeLessThan(6000)
  })

  it("uses the ja-JP report title prefix and labels when cfg.locale is ja-JP", () => {
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const html = renderBanner(
      { title: "OpenAI", type: "schema:Organization", lang: "ja", review_status: "reviewed" },
      { slug: "ja/organization/openai", cfg: { locale: "ja-JP", baseUrl: "example.github.io/wiki" } },
    )
    expect(html).toContain(encodeURIComponent("[報告] Organization: OpenAI"))
    expect(html).toContain(encodeURIComponent("ページ: https://example.github.io/wiki/ja/organization/openai"))
    expect(html).toContain(encodeURIComponent("言語: ja"))
    expect(html).toContain("気づいた点を報告する")
  })

  // Issue #378: WikiCommitBanner used to key captions off cfg.locale (a
  // site-wide setting) unconditionally, so a bilingual wiki's en/ pages
  // showed Japanese captions whenever quartz.config.yaml's locale was ja-JP,
  // and vice versa. frontmatter.lang now takes priority per page.
  it("uses English labels for an en page even when cfg.locale is ja-JP", () => {
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const html = renderBanner(
      { title: "OpenAI", lang: "en", review_status: "reviewed" },
      { slug: "en/organization/openai", cfg: { locale: "ja-JP" } },
    )
    expect(html).toContain("Report something you noticed")
    expect(html).not.toContain("気づいた点を報告する")
  })

  it("falls back to cfg.locale when frontmatter.lang is absent", () => {
    const html = renderBanner(
      { title: "OpenAI", review_status: "pending" },
      { cfg: { locale: "ja-JP" } },
    )
    expect(html).toContain("LLM が自動生成したページです")
  })

  it("falls back to cfg.locale when frontmatter.lang is not a locale this plugin ships", () => {
    const html = renderBanner(
      { title: "OpenAI", lang: "fr", review_status: "pending" },
      { cfg: { locale: "ja-JP" } },
    )
    expect(html).toContain("LLM が自動生成したページです")
  })

  // Issue #742: Issue #665 fixed the tracking Issue telling readers to close an
  // Issue they cannot close. One layer below it, the report link this banner
  // shows every reader (Issue #245) lands on a login wall for anyone without a
  // GitHub account — measured: `/issues/new?...` redirects to
  // `login?return_to=<the whole URL>` and returns "Sign in to GitHub". What is
  // fixed here is only that the link gave no warning; no account-free route is
  // added (that would mean an external service, and the design keeps no
  // external state).
  describe("the report link says an account is needed (Issue #742)", () => {
    it("states it next to the link on a pending page", () => {
      const html = renderBanner({ title: "OpenAI", review_status: "pending" })
      expect(html).toContain("(GitHub account required)")
    })

    it("states it on the report-link-only row a build-generated index page gets", () => {
      // Same branch as "renders only the report link on a reviewed page that
      // records no generation" above: no generation stamp, so the banner body
      // never renders and only this row carries the link.
      const html = renderBanner({ title: "山田太郎", review_status: "reviewed" })
      expect(html).toContain("wikicommit-banner__report")
      expect(html).not.toContain("wikicommit-banner--pending")
      expect(html).toContain("(GitHub account required)")
    })

    it("states it on a reviewed page that does record generation", () => {
      const html = renderBanner({
        title: "OpenAI",
        review_status: "reviewed",
        generated_at: "2026-06-17",
        generated_by: "claude-opus-5",
      })
      expect(html).toContain("wikicommit-banner--reviewed")
      expect(html).toContain("(GitHub account required)")
    })

    it("follows the page's own language, like the link label it annotates", () => {
      const html = renderBanner(
        { title: "OpenAI", lang: "ja", review_status: "pending" },
        { cfg: { locale: "en-US" } },
      )
      expect(html).toContain("（GitHub アカウントが必要）")
      expect(html).not.toContain("(GitHub account required)")
    })

    it("keeps the note out of the link label so the call to action stays clean", () => {
      // The constraint Issue #742 carries over from Issue #738: say the fact
      // without making the banner heavier. Folding it into the anchor would
      // render it underlined and coloured like the action itself.
      const html = renderBanner({ title: "OpenAI", review_status: "pending" }) as string
      const anchorText = /<a [^>]*class="wikicommit-banner__link"[^>]*>([^<]*)<\/a>/.exec(
        html.slice(html.indexOf("wikicommit-banner__report-action")),
      )?.[1]
      expect(anchorText).toBeDefined()
      expect(anchorText).not.toContain("GitHub account required")
      expect(html).toContain('class="wikicommit-banner__link-note"')
    })

    it("keeps the note in the same wrapping unit as the link it annotates", () => {
      // Both rows are flex-wrap: wrap and already hold a second item, so a bare
      // note as a further sibling could wrap onto its own line and read as
      // attached to nothing.
      const html = renderBanner({ title: "OpenAI", review_status: "pending" }) as string
      const wrapper = /<span class="wikicommit-banner__report-action">([\s\S]*?)<\/span><\/div>/.exec(html)?.[1]
      expect(wrapper).toBeDefined()
      expect(wrapper).toContain("wikicommit-banner__link")
      expect(wrapper).toContain("wikicommit-banner__link-note")
    })

    it("announces the note with the link for a reader moving by link list", () => {
      // The note only warns readers who see it next to the label. Someone
      // tabbing through links, or reading a generated list of them, gets the
      // label alone unless the two are tied together — and that is one of the
      // groups this note exists for.
      const html = renderBanner({ title: "OpenAI", review_status: "pending" }) as string
      expect(html).toContain('aria-describedby="wikicommit-banner-report-note"')
      expect(html).toContain('id="wikicommit-banner-report-note"')
    })

    it("does not leak into the prefilled report body", () => {
      // The note is guidance for reaching the form, not something the reporter
      // is submitting — the same line Issue #738 drew for its own guidance.
      vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
      const html = renderBanner({ title: "OpenAI", review_status: "pending" }) as string
      const href = /href="([^"]*)"/.exec(html.replace(/&amp;/g, "&"))?.[1]
      expect(href).toBeDefined()
      expect(decodeURIComponent(href as string)).not.toContain("GitHub account required")
    })
  })

  // Issue #751: Pass 4 checks every generated page against its own sources and,
  // since Issue #750, records the verdict. convert_wikilinks.py reads that record
  // at build time and stamps it onto the published copy — so these two fields
  // exist on pages under content/ and on no page in .wikicommit/entity/, which is
  // what lets a verdict be withheld the moment the page changes under it.
  describe("the source check the page passed (Issue #751)", () => {
    const withVerdict = {
      title: "OpenAI",
      review_status: "pending",
      generated_at: "2026-06-17",
      generated_by: "claude-opus-5",
      ai_review_at: "2026-09-05",
      ai_review_model: "claude-opus-5[1m]",
    }

    it("shows what was checked and when, next to the generation line", () => {
      const html = renderBanner(withVerdict)
      expect(html).toContain("Checked against sources:")
      expect(html).toContain("2026-09-05")
      expect(html).toContain("claude-opus-5[1m]")
    })

    it("shows the same line on a reviewed page", () => {
      // Same reasoning that collapsed the two branches in Issue #739: passing
      // the source check is a fact about how the page was made, and a person
      // reading it later neither adds to that nor takes it away.
      const html = renderBanner({ ...withVerdict, review_status: "reviewed" })
      expect(html).toContain("wikicommit-banner--reviewed")
      expect(html).toContain("Checked against sources:")
    })

    it("says nothing at all when the page carries no verdict", () => {
      // Three cases reach here and all three must render as this banner did
      // before the feature existed: no record, a record gone stale, an
      // unreadable one. The page cannot tell them apart, and should not try.
      const html = renderBanner({
        title: "OpenAI",
        review_status: "pending",
        generated_at: "2026-06-17",
        generated_by: "claude-opus-5",
      })
      expect(html).not.toContain("Checked against sources:")
      expect(html).not.toContain("wikicommit-banner__ai-review")
    })

    it("says nothing when only one of the two fields is present", () => {
      // Half a line ("checked on <blank>") is worse than none.
      expect(renderBanner({ ...withVerdict, ai_review_model: undefined })).not.toContain(
        "Checked against sources:",
      )
      expect(renderBanner({ ...withVerdict, ai_review_at: undefined })).not.toContain(
        "Checked against sources:",
      )
      expect(renderBanner({ ...withVerdict, ai_review_at: "  " })).not.toContain(
        "Checked against sources:",
      )
    })

    it("does not claim the page was verified", () => {
      // Pass 4 compares the page with its own sources and nothing else:
      // completeness is out of scope (Issue #722), and harm and conflicts with
      // the reader's knowledge are seen by no layer (Issue #723). Over-claiming
      // here would repeat, in the opposite direction, the error Issue #740 is
      // correcting for `reviewed`.
      const html = renderBanner(withVerdict) as string
      const line = /<p class="wikicommit-banner__ai-review">([\s\S]*?)<\/p>/.exec(html)?.[1]
      expect(line).toBeDefined()
      expect(line).not.toMatch(/verified|accurate|correct|complete/i)
    })

    it("carries no finding count", () => {
      // Aggregated on the overview page instead: "2 findings" beside one page
      // reads as "this page is bad" when it means a finding was raised and the
      // page rewritten until it passed.
      const html = renderBanner({ ...withVerdict, ai_review_findings: 2 }) as string
      expect(html).not.toContain("findings")
      expect(html).not.toContain(">2<")
    })

    it("follows the page's own language", () => {
      const html = renderBanner(
        { ...withVerdict, lang: "ja" },
        { cfg: { locale: "en-US" } },
      )
      expect(html).toContain("出典と照合:")
      expect(html).toContain("照合モデル:")
      expect(html).not.toContain("Checked against sources:")
    })
  })

  it("falls back to '#' for the report link when GITHUB_REPOSITORY is unset", () => {
    vi.stubEnv("GITHUB_REPOSITORY", "")
    const html = renderBanner({ title: "OpenAI", review_status: "reviewed" })
    expect(html).toContain('href="#"')
  })

  it("renders nothing on a removed page, even when review_status is reviewed", () => {
    const html = renderBanner({ title: "OpenAI", review_status: "reviewed", status: "removed" })
    expect(html).toBeNull()
  })

  it("renders nothing on a removed page that is still pending", () => {
    const html = renderBanner({ title: "OpenAI", review_status: "pending", status: "removed" })
    expect(html).toBeNull()
  })

  // Issue #407: convert_wikilinks.py's generate_root_index() embeds site-wide
  // counts as frontmatter on the build-generated content/index.md only.
  // WikiCommitBanner renders them whenever they're present, regardless of slug
  // — see the component's own comment on why it doesn't hardcode
  // fileData.slug === "index".
  it("renders the site summary when wikicommit_page_count/reviewed_count are present", () => {
    const html = renderBanner({
      title: "Wiki",
      review_status: "reviewed",
      wikicommit_page_count: 42,
      wikicommit_reviewed_count: 30,
    })
    expect(html).toContain("wikicommit-site-summary")
    expect(html).toContain("42")
    expect(html).toContain("30")
  })

  // Issue #664: "Reviewed: 0" on the front page reads as "nobody cares about
  // this project" to a first-time reader. The number stays — hiding it gives up
  // the honesty it was added for — and a caption says what it counts.
  describe("review-count caption", () => {
    it("explains what the count means, keeping the number", () => {
      const html = renderBanner({
        title: "Wiki",
        review_status: "reviewed",
        wikicommit_page_count: 486,
        wikicommit_reviewed_count: 0,
      })
      expect(html).toContain("wikicommit-site-summary__note")
      expect(html).toContain("486")
      // The zero is still shown; only its framing changed.
      expect(html).toContain(">0<")
      expect(html).toContain("published as soon as an LLM generates it")
    })

    it("does not invite the reader to review anything", () => {
      // This wiki does not take outside reviewers, so a call to participate
      // would be addressed to someone who cannot act on it.
      const html = renderBanner({
        title: "Wiki",
        review_status: "reviewed",
        wikicommit_page_count: 486,
        wikicommit_reviewed_count: 0,
      })
      for (const word of ["Help", "help review", "Join", "Contribute", "Sign up"]) {
        expect(html).not.toContain(word)
      }
    })

    it("uses the Japanese caption on a ja root page", () => {
      const html = renderBanner({
        title: "Wiki",
        lang: "ja",
        review_status: "reviewed",
        wikicommit_page_count: 486,
        wikicommit_reviewed_count: 0,
      })
      expect(html).toContain("人が読んで確認:")
      expect(html).toContain("人が最後まで読み、明らかな問題を見つけなかった件数")
    })

    it("is not rendered on a page without the site summary", () => {
      const html = renderBanner({ title: "山田太郎", review_status: "reviewed" })
      expect(html).not.toContain("wikicommit-site-summary__note")
    })
  })

  // Issue #769: the AI review count reached the per-page banner and the overview
  // page but not the front page — the one surface Issue #664 had already judged to be
  // the most easily misread. Without it, "95 pages / 12 read by a person" reads
  // as "nothing has been done to the other 83".
  describe("AI review count", () => {
    it("renders the count and its own note when wikicommit_ai_reviewed_count is present", () => {
      const html = renderBanner({
        title: "Wiki",
        review_status: "reviewed",
        wikicommit_page_count: 95,
        wikicommit_reviewed_count: 12,
        wikicommit_ai_reviewed_count: 83,
      })
      expect(html).toContain("Checked against sources:")
      expect(html).toContain(">83<")
      // Two notes now: the human one and the AI one.
      expect(html?.match(/wikicommit-site-summary__note/g)).toHaveLength(2)
    })

    it("names what the check does not cover, not only what it does", () => {
      // Stating only what was checked would rebuild, facing the other way, the
      // overstatement Issue #740 removed from "read by a person".
      const html = renderBanner({
        title: "Wiki",
        review_status: "reviewed",
        wikicommit_page_count: 95,
        wikicommit_reviewed_count: 12,
        wikicommit_ai_reviewed_count: 83,
      })
      expect(html).toContain("not completeness")
      expect(html).toContain("not the effect on real people and organizations")
      expect(html).toContain("not conflicts with what you know")
    })

    it("omits the count and its note when the field is absent", () => {
      // Absence means "no record" (a wiki predating review records, or a
      // language of nothing but translation pages), not "nothing was checked".
      const html = renderBanner({
        title: "Wiki",
        review_status: "reviewed",
        wikicommit_page_count: 95,
        wikicommit_reviewed_count: 12,
      })
      expect(html).toContain("wikicommit-site-summary")
      expect(html).not.toContain("Checked against sources:")
      expect(html?.match(/wikicommit-site-summary__note/g)).toHaveLength(1)
    })

    it("ignores a non-numeric value left on a stale content/index.md", () => {
      const html = renderBanner({
        title: "Wiki",
        review_status: "reviewed",
        wikicommit_page_count: 95,
        wikicommit_reviewed_count: 12,
        wikicommit_ai_reviewed_count: "83",
      })
      expect(html).not.toContain("Checked against sources:")
    })

    it("uses the Japanese labels on a ja root page", () => {
      const html = renderBanner({
        title: "Wiki",
        lang: "ja",
        review_status: "reviewed",
        wikicommit_page_count: 95,
        wikicommit_reviewed_count: 12,
        wikicommit_ai_reviewed_count: 83,
      })
      expect(html).toContain("出典と照合:")
      expect(html).toContain("網羅性・実在の人物や組織への影響")
    })

    it("does not describe the human count as a sample", () => {
      // Issue #769 keeps sampling vocabulary out of reader-facing copy: whether
      // RISKY: actually selects is still unmeasured, and the word alone would
      // imply a formal sampling design exists.
      const html = renderBanner({
        title: "Wiki",
        review_status: "reviewed",
        wikicommit_page_count: 95,
        wikicommit_reviewed_count: 12,
        wikicommit_ai_reviewed_count: 83,
      })
      for (const word of ["sample", "Sample", "sampling", "抜取", "サンプリング"]) {
        expect(html).not.toContain(word)
      }
    })
  })

  // Issue #670: config.yml's `theme` is an LLM-facing scope instruction, not
  // reader-facing copy, so the banner no longer renders it. A stale
  // wikicommit_theme left on a previously built content/index.md must not
  // resurrect the line.
  it("never renders a theme line, even when wikicommit_theme is present", () => {
    const html = renderBanner({
      title: "Wiki",
      review_status: "reviewed",
      wikicommit_page_count: 5,
      wikicommit_reviewed_count: 2,
      wikicommit_theme: "社内技術ナレッジベース",
    })
    expect(html).toContain("wikicommit-site-summary")
    expect(html).not.toContain("wikicommit-site-summary__theme")
    expect(html).not.toContain("社内技術ナレッジベース")
  })

  it("does not render the site summary on an ordinary page (no wikicommit_page_count)", () => {
    const html = renderBanner({ title: "山田太郎", review_status: "reviewed" })
    expect(html).not.toContain("wikicommit-site-summary")
  })

  it("renders the site summary alongside the pending banner when the root page happens to be pending", () => {
    const html = renderBanner({
      title: "Wiki",
      review_status: "pending",
      wikicommit_page_count: 1,
      wikicommit_reviewed_count: 0,
    })
    expect(html).toContain("wikicommit-site-summary")
    expect(html).toContain("wikicommit-banner--pending")
  })

  it("renders a zero page count (brand-new wiki) rather than omitting the summary", () => {
    const html = renderBanner({
      title: "Wiki",
      review_status: "reviewed",
      wikicommit_page_count: 0,
      wikicommit_reviewed_count: 0,
    })
    expect(html).toContain("wikicommit-site-summary")
  })

  it("strips a trailing slash from cfg.baseUrl before building the page URL", () => {
    vi.stubEnv("GITHUB_REPOSITORY", "wikicommit-dev/example-wiki")
    const html = renderBanner(
      { title: "OpenAI", review_status: "reviewed" },
      { slug: "ja/organization/openai", cfg: { baseUrl: "example.github.io/wiki/" } },
    )
    expect(html).toContain(
      encodeURIComponent("Page: https://example.github.io/wiki/ja/organization/openai"),
    )
  })
})
