export default {
  components: {
    wikicommitBanner: {
      // Issue #774: the heading states a fact that is true of the page in
      // either state, so it no longer swaps. "Nobody has read this page yet"
      // (Issue #740) was false in front of the person reading it: what it
      // actually said was that no read by someone with write access had been
      // recorded, a distinction most readers do not hold. Dropping it is what
      // finally makes the heading obey Issue #739's principle — review adds a
      // line, it does not retract a warning — because a heading that swaps
      // forces the pending side to say *something*, and the only thing left to
      // say there is a negation. Issue #751 had to land first: with the
      // machine's own source check stated a line below, dropping the claim
      // about reading cannot be read as "nothing has been done to this page".
      title: "This page was generated by an LLM",
      // Split from the heading (Issue #774): the heading carries the fact, this
      // carries what follows from it. Before the split the two said nearly the
      // same thing.
      body: "It may contain inaccuracies.",
      generatedAt: "Generated:",
      generatedBy: "Model:",
      translatedAt: "Translated:",
      translatedBy: "Model:",
      // Issue #800: a sentence with a {name} placeholder rather than a bare
      // "label: value" pair, because the line now states what the reading
      // found as well as who did it. The renderer splits on {name} and puts
      // the profile link in the gap. `counts` in convert_wikilinks.py already
      // uses placeholders this way, so this is not a new pattern here.
      readBy: "Read by {name} — nothing obviously wrong stood out",
      // Issue #774: what `titleReviewed` used to be, moved out of the heading
      // and into the line review adds. It is shown only when `reviewed_by` is
      // absent — a route B page (`/wikicommit-review` runs locally and cannot
      // obtain a GitHub login) or one reviewed before that field existed. With
      // a name, the `readBy` line below says the same thing and says who,
      // and printing both would repeat "read" twice. Having this fallback is
      // what keeps the two states distinguishable without depending on
      // `reviewed_by` being present.
      readByAPerson: "A person read this page — nothing obviously wrong stood out",
      // Issue #751: what the machine check actually compared, stamped onto the
      // published copy of the page by convert_wikilinks.py and present on no
      // page in .wikicommit/entity/. Worded as "checked against its sources"
      // rather than "reviewed" or "verified": Pass 4 compares the page with the
      // documents it was written from and nothing else — completeness is
      // explicitly out of scope (Issue #722), and harm and conflicts with the
      // reader's own knowledge are seen by no layer at all (Issue #723).
      // Over-claiming here would repeat, in the opposite direction, the error
      // Issue #740 is correcting for `reviewed`.
      aiReviewAt: "Checked against sources:",
      aiReviewBy: "Checking model:",
      unknown: "unknown",
      reviewStatusLink: "Check this page's review status",
      reportLink: "Report something you noticed",
      // Issue #742: for a reader without a GitHub account this link lands on a
      // login wall — `/issues/new?...` redirects to `login?return_to=<the whole
      // URL>`, so the form is never shown. Issue #665 fixed the same shape of
      // error one layer up (the tracking Issue told readers to close an Issue
      // they have no permission to close); this is the layer below it. The
      // prefilled title and body do survive signing in, so the only thing left
      // to fix is that the link gives no warning — hence a statement of fact,
      // not a recruiting line. Kept out of the link label so the call to action
      // stays the loudest thing in the row (the visual-weight constraint this
      // shares with Issue #738).
      reportLinkAccountNote: "(GitHub account required)",
      reportTitlePrefix: "[Report]",
      reportBodyPage: "Page:",
      reportBodyLanguage: "Language:",
      reportBodyOriginal: "Original page:",
      // Issue #738: the two checklist items Issue #723 marked "only a person
      // can check this" reach only whoever browses the repository's Issue
      // list — in practice the operator. The reader most likely to notice the
      // harm item is usually the subject of the page, who never opens that
      // list but does read the page. This guidance rides the report link
      // instead, which every reader sees.
      reportBodyGuidanceHeading:
        "These are the kinds of problem no automated check can find. Write down any that apply (you are not being asked to go looking — only what you noticed while reading).",
      reportBodyGuidanceHarm:
        "- Anything about a real person or organization that felt overstated or too certain",
      reportBodyGuidanceKnowledge:
        "- Anything that conflicts with what you know (add a URL if you have one)",
      reportBodyGuidanceContradiction: "- Anything another page on this wiki says differently",
      // Not a closed list: a typo, a stale fact or a dead link is just as
      // welcome. Stated so the bullets above do not read as "report nothing
      // else".
      reportBodyGuidanceFooter:
        "Anything else is welcome too — typos, stale facts, broken links.",
      // The heading gives the reporter a marked place to write. `body=`
      // replaces report.md's own `## Page` / `## Problem` headings entirely, so
      // without this the prefilled body ends at the guidance and there is
      // nowhere obvious to type. The page facts above need no heading of their
      // own — each line already labels itself.
      reportBodyProblemHeading: "## Problem",
      siteSummaryPages: "Pages:",
      siteSummaryReviewed: "Read and checked by a person:",
      siteSummaryReviewNote: "Every page is published as soon as an LLM generates it. The check against sources is run by machine; \"read and checked by a person\" is how many pages someone has since read all the way through without anything obviously wrong standing out. Only some pages are read by a person, by design — this number is not meant to reach the total, and it is not a complete quality guarantee.",
      siteSummaryAiReviewed: "Checked against sources:",
      siteSummaryAiReviewNote: "\"Checked against sources\" is how many pages were compared against their own sources when they were generated. That check covers agreement with those sources and nothing else — not completeness, not the effect on real people and organizations, not conflicts with what you know.",
    },
  },
}
